name: blog
services:
  mysql:
    image: 'mysql:8.3'
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3306'
